---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

# set all+grant privileges for root
- name: Update root password for all root accounts
  mysql_user: name=root host='%' check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }} priv=*.*:ALL,GRANT

- name: Create databases
  mysql_db: name={{ mysql.database }} state=present login_user=root login_password={{ mysql.root_password }}

- name: Import dump
  mysql_db: name={{ mysql.database }} state=import login_user=root login_password={{ mysql.root_password }} target=/vagrant/{{ mysql.dump }}
  when: mysql.dump

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mysql.root_password }}
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"

- name: Create users
  mysql_user: name={{ mysql.user }} password={{ mysql.password }} state=present login_user=root login_password={{ mysql.root_password }}

# set all privileges to specified user
- name: Update user password for all accounts
  mysql_user: name={{ mysql.user }} host='%' password={{ mysql.password }} login_user=root login_password={{ mysql.root_password }} priv=*.*:ALL

- name: Ensure target config directory exists
  file: path=/etc/mysql/conf.d state=directory

- name: Set own configuration 
  copy: src=vagrant.cnf dest=/etc/mysql/conf.d/vagrant.cnf
  notify: restart mysql
