---
- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install base packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-fpm

- name: Install additional packages from config
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: php.packages
  when: php.packages is defined

- include: configure.yml
#- include: pecl.yml
