---

- name: Add Repository
  sudo: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main' state=present

- name: Add Keys for Repository
  sudo: yes
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql-{{ pgsql.version }}
    - postgresql-client-{{ pgsql.version }}
    - python-pygresql
    - python-psycopg2

- name: Create databases
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ pgsql.database }} state=present

- name: Import dump
  sudo: yes
  sudo_user: postgres
  shell: psql {{ pgsql.database }} < /vagrant/{{ pgsql.dump }}
  when: pgsql.dump

- name: Create users
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ pgsql.user }} password={{ pgsql.password }} db={{ pgsql.database }} priv=ALL role_attr_flags=SUPERUSER,CREATEDB 

- name: Update configuration
  sudo: yes
  lineinfile: dest=/etc/postgresql/{{ pgsql.version }}/main/postgresql.conf regexp="^#?listen_addresses = 'localhost'" line="listen_addresses = '*'" state=present backrefs=yes owner=postgres group=postgres mode=0644

- name: Update authentication configuration
  sudo: yes
  lineinfile: dest=/etc/postgresql/{{ pgsql.version }}/main/pg_hba.conf line="host\tall\tall\t0.0.0.0/0\tmd5\t" owner=postgres group=postgres mode=0640
  notify: restart pgsql
